### ISSUE TITLE
exceltp 실행 안됨

### ISSUE THREAD

**Issue by morenice** [morenice/excellent#19]
Traceback (most recent call last):
  File "exceltp.py", line 7, in <module>
    exceltp.main()
  File "/Users/morenice/Sources/excellent/exceltp/core.py", line 83, in main
    usage()
  File "/Users/morenice/Sources/excellent/exceltp/core.py", line 72, in usage
    """ % (sys.argv[0], sys.argv[0], sys.argv[0], sys.argv[0])
TypeError: not all arguments converted during string formatting

**Comment by morenice** [comment]
hotfix
